# docker-compose.yml
version: "3.9"
services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  api:
    build: .
    environment:
      REDIS_URL: redis://redis:6379/0
      PORT: 8000
    command: uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}
    depends_on:
      - redis
    ports:
      - "8000:8000"

  worker:
    build: .
    environment:
      REDIS_URL: redis://redis:6379/0
    # RQ listens to the "scans" queue and invokes worker.run_scan_job
    command: rq worker -u ${REDIS_URL:-redis://redis:6379/0} scans
    depends_on:
      - redis
